server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.17.128:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    #url: jdbc:h2:file:./datasource/h2/jpa
    #url: jdbc:log4jdbc:h2:file:./datasource/h2/jpa
    #url: jdbc:log4jdbc:h2:tcp://localhost/./datasource/h2/jpa;AUTO_SERVER=TRUE
    username: root
    password: root
    #driver-class-name: org.h2.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource
    #type: org.apache.tomcat.jdbc.pool.DataSource
    type: com.zaxxer.hikari.HikariDataSource
    #type: org.apache.commons.dbcp.BasicDataSource
    #type: org.apache.commons.dbcp2.BasicDataSource

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format-sql: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false # 禁用在视图层仍然可以获取懒加载数据,默认SpringMVC是开启状态,会影响性能.
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  liquibase:
    contexts: dev
    drop-first: true
    enabled: true
  data:
    mongodb:
      #uri: mongodb://192.168.17.128:27017/jpa
      database: jpa
      host: 192.168.17.128
      port: 27017
      username: admin
      password: admin
    redis:
      repositories:
        #禁用redis作为Jpa的缓存数据库,后面考虑redis使用Spring框架提供的缓存管理器
        enabled: false
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: 10
        min-idle: 0
        max-idle: 4
      shutdown-timeout: 100
    host: 192.168.17.128
    port: 6379
    password: 123456
    database: 0
  rabbitmq:
    host: 192.168.17.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
    com.application: TRACE

