server:
  port: 8080
spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    #url: jdbc:h2:file:./datasource/h2/jpa
    #url: jdbc:log4jdbc:h2:file:./datasource/h2/jpa
    url: jdbc:log4jdbc:h2:tcp://localhost/./datasource/h2/jpa;AUTO_SERVER=TRUE
    username: sa
    password:
    #driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    type: com.alibaba.druid.pool.DruidDataSource
    #type: org.apache.tomcat.jdbc.pool.DataSource
    #type: com.zaxxer.hikari.HikariDataSource
    #type: org.apache.commons.dbcp.BasicDataSource
    #type: org.apache.commons.dbcp2.BasicDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  liquibase:
    contexts: dev
    drop-first: false
    enabled: true
  data:
    mongodb:
      #uri: mongodb://192.168.17.128:27017/jpa
      database: jpa
      host: 192.168.17.128
      port: 27017
      username: admin
      password: admin
    redis:
      repositories:
        #禁用redis作为Jpa的缓存数据库,后面考虑redis使用Spring框架提供的缓存管理器
        enabled: false
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: 10
        min-idle: 0
        max-idle: 4
      shutdown-timeout: 100
    host: 192.168.17.128
    port: 6379
    password: 123456
    database: 0
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
    com.application: TRACE

