server:
  port: 8080
spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:h2:file:./datasource/h2/jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    #type: com.zaxxer.hikari.HikariDataSource
    #type: org.apache.commons.dbcp.BasicDataSource
    #type: org.apache.commons.dbcp2.BasicDataSource
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    drop-first: false
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      springframework:
        INFO
